### ISSUE TITLE
Flaky pattern matches don't seem to affect build UI

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#11]
Go to https://circle.pytorch.org/commit-details.html?sha1=835a6b9da29dfc7261586b245592c438773791c0

Notice that the matched pattern is a flaky test. What I would like to see is "build succeeded, but some tests failed with flaky errors". I don't see anything like that on the page.

**Comment by kostmo** [comment]
If all of the failures were flaky, I'll now indicate that on the page, but for now I'm going to go with weaker language than declaring that the build succeeded.
