### ISSUE TITLE
automatically tag certain people upon certain failing builds

### ISSUE THREAD

**Issue by kostmo** [kostmo/circleci-failure-tracker#13]
Specific request was:
> add a rule like "if everything else passed but not xla, tag/email Ailing"

**Comment by kostmo** [comment]
More context from Brian V.:
> is there a way we could set it up such that the XLA tests always run, notify you on failure, maybe tag the ticket, but don't actually fail the CI build overall?
It would be great if we could get to a point where we can assume a failed build is actually not landable. We're getting close, but failing ignorable tests on master would bring us back to regular periods where we have to look at individual tests to determine if a red build is actually bad.

Karl says:
> Closest thing to this may be a summary produced by dr.ci.  It would interpret the list of failed builds and give a determination of landability

Here's where I'm brewing this landability logic: https://github.com/kostmo/circleci-failure-tracker/blob/c64c46d5f06d333f9250d187ab55a2ace20d7004/app/static/script/commit-details.js#L19-L27

**Comment by kostmo** [comment]
## Short term plan of action

Will automatically add a comment to the user's PR with a ping to Ailing's username if the XLA build reports failure.

## Caveats
There is some concern about signal-to-noise ratio of automatically sending a message when XLA breaks on someone's random PR build.  In the long term it may be best for the human contributor to make the final determination whether to reach out.

**Comment by ailzhang** [comment]
Please also add @dlibenzi and @asuhan :P Thanks a lot for taking care of this!

**Comment by nairbv** [comment]
Another option could be a process where we make it easy to turn XLA tests on/off. If an XLA test fails in a PR, we could just notify @ailzhang, turn the test off, and merge it. Then when Ailing fixes the issue on master, she turns the test back on. That way master is never broken, and the failed test in a PR is still useful signal to the developer.

**Comment by ailzhang** [comment]
@nairbv I think turn it on and off could potentially lead to missed signal if another breakage lands when it's turned off, it'd hard for us to track back who break us.

**Comment by nairbv** [comment]
> @nairbv I think turn it on and off could potentially lead to missed signal if another breakage lands when it's turned off, it'd hard for us to track back who break us.

If someone pushes to master with the test failing, won't the signal for another breakage be missed anyway?

**Comment by dlibenzi** [comment]
It feels to me that letting PR breaking code in, encourages a "Better say sorry than asking permission" behavior.
If we are engaged as soon as the breakage happen, there should not be much delay.
The problematic PRs are usually the ones which are pretty big, and require quite some time to develop and test.
That time, assuming we are engaged as soon as the developer sees red on the CI/xla, will give us time to fix on our side, and/or collaborate with the developer for an alternative solution which pleases both sides.
