### ISSUE TITLE
Increase the log context

### ISSUE THREAD

**Issue by suo** [kostmo/circleci-failure-tracker#14]
The log context is super cool! However, it's too small right now 😞, so it's sometimes hard to see stack traces/expect file diffs. Would it be possible to increase the context to, say, 100 lines? 

The ideal interface would be a "see more" on either side of the log so the user could expand it in either direction if necessary, but I'm not sure how much harder that is to implement.

**Comment by kostmo** [comment]
Increased to up to 50 lines of context for now.
