### ISSUE TITLE
HUD __dr.ci doesn't seem very useful

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#3]
It seems to just always be a red X: https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master

**Comment by kostmo** [comment]
As it is today, it refrains from posting a status if all the builds are green.  There are ~10 commits in the screenshot below in which this was the case.  Alternatively, I could make it post its own green status if everything is green.  Which would be better?

![Screen Shot 2019-06-12 at 4 59 07 PM](https://user-images.githubusercontent.com/261693/59394144-8bcfa300-8d33-11e9-842a-f719437b07ad.png)

**Comment by kostmo** [comment]
Disabled in favor of PR commenter bot.
