### ISSUE TITLE
Modal dialogue is too big; it looks like a new page

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#31]
Steps to reproduce:
1. Go to https://circle.pytorch.org/commit-details.html?sha1=6d7cc4cc7744f646a397ceb9e887e0f8ad519850
2. Click on one of the build logs to expand
3. Observe that modal covers up entire page

Expected result: Back button works to get me back to index page + I can middle click to open the log in another page

Actual result: None of these work

**Comment by kostmo** [comment]
Console log dialog size-limited in 38913bb.  Middle click also works to open full plaintext log in another page.
