### ISSUE TITLE
Specificity gets confused about tests which purposely trigger compile errors

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#32]
In https://circle.pytorch.org/commit-details.html?sha1=6d7cc4cc7744f646a397ceb9e887e0f8ad519850 the compile error regex matches a useless "ERROR:sccache::server: Compilation failed" line, when "ERROR: test_compilation_error_formatting (__main__.TestCppExtension)" is a much better line (it also has a pattern, but it is less specific). Does this mean the test matcher should have higher specificity than build error?

**Comment by kostmo** [comment]
>  Does this mean the test matcher should have higher specificity than build error?

Yep, that seems right.
