### ISSUE TITLE
Alt click doesn't work on master table

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#33]
Steps to reproduce:
1. Go to https://circle.pytorch.org/master-timeline.html
2. Alt-click on an X

Expected result: Opens in new tab
Actual result: Does not

**Comment by kostmo** [comment]
Now using `<a href=..` instead of a javascript `onclick` handler for build indicators, so "Command-click" (on Mac) now opens them in a new tab.
