### ISSUE TITLE
Master timeline does not preserve offset/count on refresh

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#34]
Steps to reproduce:
1. Go to https://circle.pytorch.org/master-timeline.html
2. Set count to 100
3. Refresh

Expected result: It's still 100
Actual result: It goes back to the default

**Comment by kostmo** [comment]
Fixed: Form values are now encoded in the URL after clicking the "Go" button (or hitting Enter in a form field).
