### ISSUE TITLE
Use Aho–Corasick algorithm to batch pattern matching on literal expressions

### ISSUE THREAD

**Issue by kostmo** [kostmo/circleci-failure-tracker#39]
Use ["Alfred–Margaret"](https://tech.channable.com/posts/2019-03-13-how-we-made-haskell-search-strings-as-fast-as-rust.html) Haskell implementation.

**Comment by ezyang** [comment]
If you want regexes to work you can do https://github.com/livegrep/livegrep Nelson has blogged about the algorithm at https://blog.nelhage.com/2015/02/regular-expression-search-with-suffix-arrays/
