### ISSUE TITLE
Build page should show all pattern matches, not just the best one

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#48]
On https://dr.pytorch.org/build-details.html?build_id=11847231 I only see one pattern match. But it's not actually the one I want because it grabs the wrong log line; i.e., not the one with the actual error message. I suspect there is another pattern that gives me the info I want. But the UI tells me that this shows the "best" pattern match only. Show me all of them!

**Comment by kostmo** [comment]
The "all matches" table is hidden when there is only one match.  I've now added a "Only 1 pattern match was found in the entire log" note when that's the case to make it less confusing.
