### ISSUE TITLE
Build page loading is slow

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#49]
https://dr.pytorch.org/build-details.html?build_id=11847231 took several seconds to load. This should be instantaneous.

**Comment by kostmo** [comment]
Performance of the [`best-build-match` API endpoint](https://dr.pytorch.org/api/best-build-match?build_id=13620566) has been improved:

| Version | Time |
| --- | --- |
| Original | 17.5 sec |
| After 397efa1eccfcc8fc6f4a7fde4a353db0b35063bb | 7.6 sec |
| After d97c6acc890fbc8039690ef28d87d9ee12cfb4d0 | 4.7 sec |

However, given that the [commit builds query was reduced to **1.9 sec**](https://github.com/kostmo/circleci-failure-tracker/issues/52#issuecomment-527252443), there should be even more room for improvement here.

**Comment by kostmo** [comment]
As of da1732a, the commit page and build page load in 1 second or less.
