### ISSUE TITLE
No way to easily get to full log from abbreviated log

### ISSUE THREAD

**Issue by ezyang** [kostmo/circleci-failure-tracker#5]
Steps to reproduce:
1. Go to https://circle.pytorch.org/commit-details.html?sha1=835a6b9da29dfc7261586b245592c438773791c0/console
2. Click on a match (to show log context)

Expected result: Some way to get more context / get the full log

Actual result: Truncated log, with no way of seeing more

**Comment by kostmo** [comment]
Fix is deployed.  Please clear your browser's cache.
