### ISSUE TITLE
button to reveal 1000 extra lines of log context

### ISSUE THREAD

**Issue by kostmo** [kostmo/circleci-failure-tracker#53]
These extra lines shall be preloaded so that revealing is instantaneous.

**Comment by kostmo** [comment]
`+1000` button is now implemented:
![Screen Shot 2019-09-03 at 3 32 26 PM](https://user-images.githubusercontent.com/261693/64213064-6220a680-ce60-11e9-9ad2-cb1fa91c15a3.png)

FYI @soumith

**Comment by soumith** [comment]
sweet!
