### ISSUE TITLE
rebase instructions: `origin` might not be main pytorch repo

### ISSUE THREAD

**Issue by kostmo** [kostmo/circleci-failure-tracker#78]
See [this comment](https://github.com/pytorch/pytorch/pull/34324#issuecomment-599056674).  Somebody's fork, using the remote named `origin`, might not contain the `viable/strict` branch, in which case they see the error message:

```
fatal: Needed a single revision
invalid upstream 'viable/strict'
```

Current rebase advice:

> ```git fetch origin viable/strict```
> ```git rebase viable/strict```

Proposed new advice:

> ```git fetch https://github.com/pytorch/pytorch viable/strict```
> ```git rebase FETCH_HEAD```

cc @ezyang, @mpariente

**Comment by mpariente** [comment]
Thanks for looking into this.
Was I wrong about this? 
I couldn't make it work otherwise.

**Comment by kostmo** [comment]
More specifically, I think the problem is that `viable/strict` did not exist as a local branch.  To avoid forcing users to create this local branch, and to not tie it to any specific named remote, I propose this as the rebase instructions:

```
git fetch https://github.com/pytorch/pytorch viable/strict
git rebase FETCH_HEAD
```

@ezyang, what do you think?

**Comment by ezyang** [comment]
You could do that. I personally always say `git rebase origin/viable/strict` to prevent it from being ambiguous.
